#!/bin/sh

DOCKER_CREDS="$HOME/.config/gcloud/docker_credentials.json"
if [ "$1" = "get" ]; then
  if [ -f "$DOCKER_CREDS" ]; then
    local_date=`date +%Y-%m-%dT%H:%M:%S.%s`
    expiry=`jq < "$DOCKER_CREDS" '.gcrCreds.token_expiry' -r`
    if [ "$local_date" \< "$expiry" ]; then
      jq < "$DOCKER_CREDS" '.gcrCreds | {"Secret": .access_token, "Username": "oauth2accesstoken", "ServerURL": ""}' -M
      exit 0
    fi
  fi
fi
docker-credential-gcr "$@"
