#!/bin/bash

set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
TOKEN_FILE="$SCRIPT_DIR/.gcr-token"

refresh_token() {
  gcloud config config-helper --force-auth-refresh --format='value(credential.access_token)' > "$TOKEN_FILE"
}

if [ "$1" = "get" ]; then
  if [ ! -f "$TOKEN_FILE" ] || [ -n "$GCR_AUTH_REFRESH" ]; then
    refresh_token
  else
    TOKEN_AGE=$(stat -L -f %Y "$TOKEN_FILE")
    if (( TOKEN_AGE > 3600 )); then
      refresh_token
    fi
  fi

  token=$(cat "$TOKEN_FILE")

  echo "{\"Secret\": \"$token\", \"Username\": \"oauth2accesstoken\", \"ServerURL\":\"\"}"
  exit 0
fi
docker-credential-gcr "$@"
